### ISSUE TITLE
DegitError: could not find commit hash for HEAD - Windows 11

### ISSUE THREAD

**Issue by dk865** [ConstructFund/c3ide2-cli#6]
When I run it, I keep getting this error:

```
creating addon ...
? Select addon type ... plugin
? Enter addon name ... MidiPro
? Enter author name ... dk865
creating addon ...
type: plugin
name: MidiPro
author: dk865
cloning plugin template ...
addon folder dk865_midipro created successfully
DegitError: could not find commit hash for HEAD
    at Degit._cloneWithTar (C:\snapshot\c3ide2-cli\node_modules\degit\dist\index-688c5d50.js:14258:10)
    at async Degit.clone (C:\snapshot\c3ide2-cli\node_modules\degit\dist\index-688c5d50.js:14096:4)
    at async cloneTemplate (C:\snapshot\c3ide2-cli\commands\scaffold.js:91:3)
    at async create (C:\snapshot\c3ide2-cli\commands\scaffold.js:27:16) {
  code: 'MISSING_REF',
  ref: 'HEAD'
}
```

Do you know how to fix this?

**Comment by skymen** [comment]
Make sure you have git installed on your machine and it's available on the PATH

**Comment by dk865** [comment]
Ohh, okay. That makes sense. I don't have admin, so I will find a portable version and have it in the same folder. Thanks!
